name: pylint demo
on: [push, pull_request]


jobs:
  testing-pylint:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
    steps:
    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install pylint
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: analyzing with python
      run: |
            pylint $(find . -name "*.py" | xargs)
            pylint --fail-under=8.0 **/*.py
             
